substitutions:
    device_name: medify-air-bedroom
    friendly_name: "Medify Air (Bedroom)"

esphome:
    name: "${device_name}"
    friendly_name: "${friendly_name}"

esp32:
    board: esp32dev
    framework:
        type: esp-idf
        advanced:
            minimum_chip_revision: "3.1"
            sram1_as_iram: true

logger:
    level: INFO

api:
    encryption:
        key: !secret medify-air-bedroom_encryption_key

ota:
    - platform: esphome
      password: !secret medify-air-bedroom_ota_password

wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

    fast_connect: true
    reboot_timeout: 15min

    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
        ssid: "${friendly_name} Fallback Hotspot"
        password: !secret ap_password

captive_portal:

# GPIO output for controlling the circuit
switch:
    - platform: template
      name: "Power"
      id: toggle_relay
      restore_mode: DISABLED
      optimistic: true

      turn_on_action:
          - switch.turn_on: toggle_relay_gpio
          - delay: 0.10s
          - switch.turn_off: toggle_relay_gpio
      turn_off_action:
          - switch.turn_on: toggle_relay_gpio
          - delay: 0.10s
          - switch.turn_off: toggle_relay_gpio

    - platform: template
      name: "Child Lock"
      id: toggle_relay_2
      restore_mode: DISABLED
      optimistic: true
      turn_on_action:
          - switch.turn_on: toggle_child_lock
          - delay: 4.10s
          - switch.turn_off: toggle_child_lock
      turn_off_action:
          - switch.turn_on: toggle_child_lock
          - delay: 4.10s
          - switch.turn_off: toggle_child_lock

    - platform: gpio
      id: toggle_relay_gpio
      pin: GPIO26

    - platform: gpio
      id: toggle_speed_gpio
      pin: GPIO32
      restore_mode: DISABLED

    - platform: gpio
      id: toggle_dimmer
      pin: GPIO13
      restore_mode: DISABLED

    - platform: gpio
      id: toggle_child_lock
      pin: GPIO33
      restore_mode: DISABLED

button:
    - platform: template
      name: "Speed"
      id: toggle_speed
      on_press:
          - switch.turn_on: toggle_speed_gpio
          - delay: 0.10s
          - switch.turn_off: toggle_speed_gpio

    - platform: template
      name: "Dimmer"
      id: dimmer
      on_press:
          - switch.turn_on: toggle_dimmer
          - delay: 0.10s
          - switch.turn_off: toggle_dimmer

    - platform: restart
      name: "${friendly_name} Restart"

sensor:
    - platform: uptime
      name: "${friendly_name} Uptime"

    - platform: wifi_signal
      name: "${friendly_name} WiFi Signal"
      update_interval: 60s

    - platform: internal_temperature
      name: "${friendly_name} Internal Temperature"

binary_sensor:
    - platform: status
      name: "${friendly_name} Status"

text_sensor:
    - platform: wifi_info
      ip_address:
          name: "${friendly_name} IP Address"
