# An ESP32 that controls an RF remote.
esphome:
    name: rf-esp32
    friendly_name: "RF ESP32"

esp32:
    board: esp32dev
    framework:
        type: esp-idf
        advanced:
            minimum_chip_revision: "3.1"
            sram1_as_iram: true

# Enable logging
logger:
    level: INFO

api:
    encryption:
        key: !secret rf_esp32_encryption_key

ota:
    - platform: esphome
      password: !secret rf_esp32_ota_password

wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

    fast_connect: true
    reboot_timeout: 15min

    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
        ssid: "Rf-ESP32 Fallback Hotspot"
        password: !secret ap_password

captive_portal:

## Receiver is only used for testing.
# remote_receiver:
#   pin: GPIO27
#   dump: raw

remote_transmitter:
    pin: GPIO23
    non_blocking: false
    carrier_duty_percent: 100% # Typical for many 433MHz devices

script:
    - id: toggle_power
      then:
          - remote_transmitter.transmit_raw:
                code: !include rf_codes/toggle_power.yaml

    - id: toggle_power2
      then:
          - remote_transmitter.transmit_raw:
                code: !include rf_codes/power_on.yaml

    - id: send_color_temp
      then:
          - remote_transmitter.transmit_raw:
                code: !include rf_codes/color_temp.yaml

    - id: send_brightness_up
      then:
          - remote_transmitter.transmit_raw:
                code: !include rf_codes/brightness_up.yaml

    - id: send_brightness_down
      then:
          - remote_transmitter.transmit_raw:
                code: !include rf_codes/brightness_down.yaml

switch:
    - platform: template
      name: "Power Button"
      optimistic: true
      restore_mode: DISABLED

      turn_on_action:
          - script.execute: toggle_power

      turn_off_action:
          - script.execute: toggle_power

    - platform: template
      name: "Power 2"
      optimistic: true
      turn_on_action:
        - remote_transmitter.transmit_raw:
            code: [
              1251, -383, 1243, -389, 1237, -395,
              427, -1208, 1238, -396, 1231, -400,
              421, -1218, 1230, -409, 1224, -407,
              416, -1219, 422, -1219, 1229, -402,
              420, -1219, 1226, -408, 414, -1219,
              1228, -409, 416, -1220, 424, -1213,
              429, -1211, 432, -1210, 434, -1205,
              437, -1203, 1245, -389, 433, -1203,
              438
            ]
            repeat:
              times: 5
              wait_time: 10ms

      turn_off_action:
        - remote_transmitter.transmit_raw:
            code: [
              1251, -383, 1243, -389, 1237, -395,
              427, -1208, 1238, -396, 1231, -400,
              421, -1218, 1230, -409, 1224, -407,
              416, -1219, 422, -1219, 1229, -402,
              420, -1219, 1226, -408, 414, -1219,
              1228, -409, 416, -1220, 424, -1213,
              429, -1211, 432, -1210, 434, -1205,
              437, -1203, 1245, -389, 433, -1203,
              438
            ]
            repeat:
              times: 5
              wait_time: 10ms

button:
    - platform: restart
      name: "RF ESP32 Restart"

    - platform: template
      name: "Color Temp"
      on_press:
          - script.execute: send_color_temp

    - platform: template
      name: "Brightness+"
      on_press:
          - script.execute: send_brightness_up

    - platform: template
      name: "Brightness-"
      on_press:
          - script.execute: send_brightness_down

    - platform: template
      name: "Brightness+ 2"
      on_press:
        - remote_transmitter.transmit_raw:
            code: [
              1379, -338, 1290, -345, 1285, -353,
              469, -1171, 1284, -357, 1271, -364,
              460, -1186, 1267, -376, 1261, -376,
              449, -1194, 454, -1194, 1261, -376,
              448, -1194, 1261, -378, 445, -1199,
              1254, -386, 441, -1202, 446, -1199,
              449, -1193, 454, -1193, 455, -1190,
              458, -1190, 1264, -375, 1255, -380,
              442,
            ]
            repeat:
              times: 5
              wait_time: 10ms

    - platform: template
      name: "Brightness- 2"
      on_press:
        - remote_transmitter.transmit_raw:
            code: [
              1229, -409, 1218, -411, 1216, -416,
              406, -1228, 1219, -417, 1209, -420,
              403, -1234, 1217, -428, 1202, -426,
              397, -1237, 408, -1232, 1216, -417,
              405, -1231, 1214, -420, 403, -1232,
              1217, -421, 405, -1232, 411, -1232,
              412, -1224, 421, -1219, 425, -1215,
              1232, -405, 1222, -408, 1220, -412,
              411,
            ]
            repeat:
              times: 5
              wait_time: 10ms

sensor:
    - platform: uptime
      name: "RF ESP32 Uptime"

    - platform: wifi_signal
      name: "RF ESP32 WiFi Signal"
      update_interval: 60s

    - platform: internal_temperature
      name: "RF ESP32 Internal Temperature"

binary_sensor:
    - platform: status
      name: "RF ESP32 Status"

text_sensor:
    - platform: wifi_info
      ip_address:
          name: "RF ESP32 IP Address"
