# An ESP32 that controls an RF remote.
esphome:
    name: rf-esp32
    friendly_name: RF ESP32

esp32:
    board: esp32dev
    framework:
        type: esp-idf
        advanced:
            minimum_chip_revision: "3.1"
            sram1_as_iram: true

# Enable logging
logger:
    level: INFO

api:
    encryption:
        key: !secret rf_esp32_encryption_key

ota:
    - platform: esphome
      password: !secret rf_esp32_ota_password

wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

    fast_connect: true
    reboot_timeout: 15min

    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
        ssid: "Rf-ESP32 Fallback Hotspot"
        password: !secret ap_password

captive_portal:

## Receiver is only used for testing.
# remote_receiver:
#   pin: GPIO27
#   dump: raw

remote_transmitter:
    pin: GPIO23
    non_blocking: false
    carrier_duty_percent: 100% # Typical for many 433MHz devices

script:
    - id: toggle_power
      then:
          - remote_transmitter.transmit_raw:
                code: !include rf_codes/toggle_power.yaml

    - id: send_color_temp
      then:
          - remote_transmitter.transmit_raw:
                code: !include rf_codes/color_temp.yaml

    - id: send_brightness_up
      then:
          - remote_transmitter.transmit_raw:
                code: !include rf_codes/brightness_up.yaml

    - id: send_brightness_down
      then:
          - remote_transmitter.transmit_raw:
                code: !include rf_codes/brightness_down.yaml

switch:
    - platform: template
      name: "Power Button"
      optimistic: true
      restore_mode: DISABLED

      turn_on_action:
          - script.execute: toggle_power

      turn_off_action:
          - script.execute: toggle_power

button:
    - platform: restart
      name: "RF ESP32 Restart"

    - platform: template
      name: "Color Temp"
      on_press:
          - script.execute: send_color_temp

    - platform: template
      name: "Brightness+"
      on_press:
          - script.execute: send_brightness_up

    - platform: template
      name: "Brightness-"
      on_press:
          - script.execute: send_brightness_down

sensor:
    - platform: uptime
      name: "RF ESP32 Uptime"

    - platform: wifi_signal
      name: "RF ESP32 WiFi Signal"
      update_interval: 60s

    - platform: internal_temperature
      name: "RF ESP32 Internal Temperature"

binary_sensor:
    - platform: status
      name: "RF ESP32 Status"

text_sensor:
    - platform: wifi_info
      ip_address:
          name: "RF ESP32 IP Address"
